### ISSUE TITLE
Any chances it gets updated to work with on **.flac** files to, the mp3genre mod ?

### ISSUE THREAD

**Issue by silv3rr** [glftpd/foo-tools#8]
_Originally posted by @terra-dude in https://github.com/glftpd/foo-tools/pull/4#issuecomment-575755075_

> Any chances it gets updated to work with on **.flac** files to, the mp3genre mod ?

First of all dont add comments to years old closed PR.. created new issue

FLAC has been on my [TODO list](https://github.com/silv3rr/foo-tools#todo) for a while, but needs all new code separate from mp3genre and no one asked for it until now. 
Feel free create a (new) PR yourself tho and i'm sure it'll get merged here, else i'd add to my fork. You could try to start creating a [module](/blob/master/src/pre/README.modules).

**Comment by terra-dude** [comment]
Sorry for that.

Think no one has noticed, or does not indicate attention to it.
Bud a update afther somany years is welcome :)
